# (1) Rode manualmente a verificação
#   $ pre-commit run --all-files
# Ele mostrará os arquivos alterados, você pode tentar rodar
# novamente e verá que está pronto para fazer commit!
# Veja: https://www.architecture-performance.fr/ap_blog/some-pre-commit-git-hooks-for-python/
# https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=30000]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
